In [84]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# **Numbers**

In [231]:
# Import data
path = '/content/drive/My Drive/Colab Notebooks/Udemy_Complete Machine Learning and Data Science/AoC/Day 4/' # create path to call file(s) in my directory 

numbers = pd.read_csv(path+'numbers.txt', header = None)
numbers

0   1   2   3   4   5   6   7   8   ...  91  92  93  94  95  96  97  98  99
0  42  44  71  26  70  92  77  45   6  ...  15  52  76   5  13  46  89  47   3

[1 rows x 100 columns]

# **Boards**

In [234]:
with open(path+'boards.txt', 'r') as file:
    input = file.read().splitlines()

unwanted_sign_in_boards = []
for i in range((len(input))):
  unwanted_sign_in_boards.append(input[i].split(' '))

without_unwanted = []
for k in range(len(unwanted_sign_in_boards)):
  for i in range(len(unwanted_sign_in_boards[k])):
    if unwanted_sign_in_boards[k][i] != '':
      #print(a[k][i])
      without_unwanted.append(unwanted_sign_in_boards[k][i])
    else:
      pass
  #print(a[4][i])

boards = np.array(without_unwanted, dtype=int)

boards = boards.reshape([100,5,5])

boards

array([[[48, 69, 68, 49, 13],
        [25, 14, 30, 74, 89],
        [16, 38, 19, 24, 29],
        [56, 97, 50, 65, 79],
        [57, 52,  5, 27, 76]],

       [[65, 69, 73, 60, 66],
        [79, 23, 95, 32, 56],
        [36, 51, 26,  1, 28],
        [76,  9,  3, 71, 77],
        [41, 15, 61, 68, 14]],

       [[77, 86, 11, 96, 50],
        [64, 35, 76, 14,  5],
        [31, 20, 53, 84, 66],
        [83, 40,  1, 28, 79],
        [15, 74, 92, 65, 39]],

       ...,

       [[30, 68, 11, 29, 13],
        [ 1, 69,  0,  9, 93],
        [33, 57, 23, 50, 71],
        [ 8, 77,  6, 25, 45],
        [34, 12, 60,  7, 28]],

       [[91, 53, 88, 47, 40],
        [77, 92, 87, 37, 84],
        [89, 95, 78, 21, 39],
        [65, 20, 54, 94, 85],
        [45, 74, 30, 49, 11]],

       [[ 3, 58, 90, 93, 96],
        [53, 66, 24, 43, 32],
        [62, 84, 19, 82, 22],
        [13, 89, 20, 97,  1],
        [15, 91, 51, 68, 49]]])

# **Part 1**
**Finding the first winner board**

In [242]:
boards_all = boards.copy()
numbers_all = numbers.copy()
buffer = np.zeros([100,5,5])

breaking = 0
round = 0

Last_Number = 0
Winner_Board = 0


for h in numbers_all.iloc[0, :]:

  for i in range(len(boards_all)):

    for j in range(len(boards_all[0])):
      count_row = 0
      count_column = 0

      for k in range(len(boards_all[0][0])):
        if boards_all[i][j][k] == h:
          buffer[i][j][k] += 1
        
      count_row += buffer[i][j].sum()
      count_column += np.transpose(buffer, (0, 2, 1))[i][j].sum()
      if count_row == 5 or count_column == 5:
        
        breaking = 1
        Last_Number = h
        Winner_Board = i

        print('Round =', round)
        print('Last number =', h)
        print('Winner board =', i)
        if count_row == 5: # and count_row == 5:
          print('By row')
        elif count_column == 5:
          print('By column')
        break

  if breaking == 1:
    break
  
  round +=1
  

Round = 22
Last number = 21
Winner board = 34
By row


In [240]:
unmarked_list = []
for i in range(len(buffer[Winner_Board])):
  for j in range(len(buffer[Winner_Board][0])):
    if buffer[Winner_Board][i][j] == 0:
      unmarked_list.append(boards[Winner_Board][i][j])

result = (np.sum(unmarked_list))*Last_Number

print('Winner Board : \n', boards[Winner_Board])
print('Unmarked list of the winner board :', unmarked_list)
print('Result =', result)


Winner Board : 
 [[32 81 21 11 31]
 [30 56  3 25 18]
 [80 96 20 65 71]
 [41 67 22 97 10]
 [93 68 17 13  1]]
Unmarked list of the winner board : [30, 56, 3, 25, 80, 96, 20, 65, 41, 67, 22, 97, 93, 68, 17, 13, 1]
Result = 16674


# **Part 2**
**Finding the last winner board**

In [248]:
boards_all = boards.copy()
numbers_all = numbers.copy()
buffer = np.zeros([100,5,5])

breaking = 0
round = 0

Last_Number = 0
Last_Winner_Board = 0

All_winners = []

for h in numbers_all.iloc[0, :]:

  for i in range(len(boards_all)):

    for j in range(len(boards_all[0])):
      count_row = 0
      count_column = 0

      for k in range(len(boards_all[0][0])):
        if boards_all[i][j][k] == h:
          buffer[i][j][k] += 1
        
      count_row += buffer[i][j].sum()
      count_column += np.transpose(buffer, (0, 2, 1))[i][j].sum()
      if count_row == 5 or count_column == 5:
        
        All_winners.append(i)
    
    if len(set(All_winners)) == 100:
      breaking = 1
      Last_Number = h
      Last_Winner_Board = i

      print('Round =', round)
      print('Last number =', h)
      print('The last winner board =', i)
        #if count_row == 5: # and count_row == 5:
        #  print('By row')
        #elif count_column == 5:
        #  print('By column')
      break

  if breaking == 1:
    break
  
  round +=1

Round = 85
Last number = 25
The last winner board = 22


In [250]:
unmarked_list = []
for i in range(len(buffer[Last_Winner_Board])):
  for j in range(len(buffer[Last_Winner_Board][0])):
    if buffer[Last_Winner_Board][i][j] == 0:
      unmarked_list.append(boards[Last_Winner_Board][i][j])

result = (np.sum(unmarked_list))*Last_Number

print('Winner Board : \n', boards[Last_Winner_Board])
print('Unmarked list of the winner board :', unmarked_list)
print('Result =', result)

Winner Board : 
 [[ 1 27 74 89  4]
 [29  9 78 48 54]
 [10 38 13 40 49]
 [71 73 79 77 17]
 [25 22 91 20  2]]
Unmarked list of the winner board : [89, 78, 48, 38, 13, 17]
Result = 7075
